# Generated by Django 4.2.2 on 2023-06-17 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Musiclist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='Song title')),
                ('artist', models.TextField(verbose_name='Artist')),
                ('audio_file', models.FileField(upload_to='music/')),
            ],
        ),
    ]
