# Generated by Django 4.2.2 on 2023-06-17 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_musiclist'),
    ]

    operations = [
        migrations.AddField(
            model_name='musiclist',
            name='access',
            field=models.TextField(blank=True),
        ),
    ]
