# Generated by Django 4.2.2 on 2023-06-17 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_musiclist_access'),
    ]

    operations = [
        migrations.AddField(
            model_name='musiclist',
            name='status',
            field=models.TextField(default='public'),
        ),
    ]
