# Generated by Django 4.2.2 on 2023-06-17 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_musiclist_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musiclist',
            name='access',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
