# Generated by Django 4.2.2 on 2023-06-17 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_musiclist_access'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musiclist',
            name='access',
            field=models.EmailField(blank=True, max_length=1000),
        ),
    ]
